name: Verify

concurrency: ${{github.workflow}}

on:
  push:
    branches:
      - develop

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
      - name: Run lint
        run: yarn run lint
      - name: Run tests
        run: yarn run test
